[package]
name = "mikktspace-rs"
version = "0.1.0"
edition = "2018"
exclude = ["/data", "/reference", "/fuzz"]

[dependencies]

[features]
default = ["std"]
std = []

# Corrects a sorting bug in the original C implementation.
# See https://github.com/mmikk/MikkTSpace/issues/5 for details
corrected-edge-sorting = []

[dev-dependencies]
mikktspace-sys = "0.1.1"
wavefront_obj = "11.0.0"